FROM python:3.12.10-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY src/ src/

ENV PYTHONPATH=/app/src

CMD ["/app/.venv/bin/python", "-Xfrozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "8000"]
