"""initial schema

Revision ID: 7691b6a04446
Revises: 
Create Date: 2026-06-01 14:34:28.277094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7691b6a04446'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'approved', 'rejected', 'manual_review', 'expired', 'abandoned', name='application_status'), server_default='pending', nullable=False),
    sa.Column('current_step_id', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resume_token', sa.Text(), nullable=False),
    sa.Column('token_expiration_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('request_id', name=op.f('uq_applications_request_id'))
    )
    op.create_index(op.f('ix_applications_resume_token'), 'applications', ['resume_token'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.Enum('approved', 'rejected', 'manual_review', name='decision_outcome'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_decisions_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_application_id'), 'decisions', ['application_id'], unique=True)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('integration_name', sa.Text(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failure', 'timeout', name='integration_status'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_integrations_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    op.create_index(op.f('ix_integrations_application_id'), 'integrations', ['application_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'blocked', 'terminated', name='step_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_steps_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_steps')),
    sa.UniqueConstraint('application_id', 'step_name', name='uix_application_step')
    )
    op.create_index(op.f('ix_steps_application_id'), 'steps', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steps_application_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_integrations_application_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_decisions_application_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_applications_resume_token'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
